# Generated by Django 5.0.6 on 2024-06-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_record_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='country',
            field=models.CharField(default='Default Country', max_length=255),
        ),
    ]
