# Generated by Django 5.0.6 on 2024-06-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_record_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='country',
        ),
    ]
